'use client'

import { useCallback, useEffect, useState } from 'react'
import Link from 'next/link'
import { ChevronLeft, ChevronRight, Mail, X } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import { formatDate } from '@/lib/utils'

type Row = { id:string;business_name:string;email:string|null;subject:string|null;last_message_at:string|null;state:'sent'|'replied';outcome:string|null;suppression:string|null }
type Message = { id:string;direction:'sent'|'received';subject:string|null;body:string|null;occurred_at:string;from:string|null;to:string|null }
type Detail = { id:string;business_name:string;email:string|null;outcome:string|null;status:string;suppression:string|null;messages:Message[];sync_notice:string }

export function CustomerInbox() {
  const [rows,setRows]=useState<Row[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0)
  const [selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<Detail|null>(null)
  const [loading,setLoading]=useState(true),[error,setError]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');const response=await fetch(`/api/customer-inbox?page=${page}&page_size=25`);const body=await response.json();setLoading(false);if(!response.ok)return setError(body.error??'Unable to load Inbox');setRows(body.data??[]);setTotal(body.total??0)},[page])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{if(!selected){setDetail(null);return}void(async()=>{const response=await fetch(`/api/customer-inbox/${selected}`);const body=await response.json();if(response.ok)setDetail(body.data);else setError(body.error??'Unable to load conversation')})()},[selected])
  const pages=Math.max(1,Math.ceil(total/25))
  return <>
    <div className="border-b border-[var(--border-subtle)] p-5"><h2 className="text-lg font-semibold text-[var(--text-primary)]">Inbox</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Replies and conversations from your outreach.</p></div>
    {error&&<p role="alert" className="m-5 text-sm text-[var(--error)]">{error}</p>}
    {loading?<p className="p-10 text-center text-sm text-[var(--text-muted)]">Loading conversations…</p>:rows.length===0?<div className="p-14 text-center"><Mail className="mx-auto text-[var(--text-muted)]"/><h3 className="mt-3 font-medium">No conversations yet</h3><p className="mt-1 text-sm text-[var(--text-muted)]">Sent outreach and safely stored replies will appear here.</p></div>:<div className="divide-y divide-[var(--border-subtle)]">{rows.map(row=><button key={row.id} onClick={()=>setSelected(row.id)} className="grid w-full gap-2 p-5 text-left hover:bg-[var(--surface-hover)] sm:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-medium text-[var(--text-primary)]">{row.business_name}</span><span className="rounded-full bg-[var(--surface-muted)] px-2 py-0.5 text-xs capitalize text-[var(--text-muted)]">{row.state}</span>{row.suppression&&<span className="rounded-full bg-rose-500/10 px-2 py-0.5 text-xs text-rose-300">Do not contact</span>}</div><p className="truncate text-sm text-[var(--text-muted)]">{row.email??'No email'}{row.subject?` · ${row.subject}`:''}</p></div><span className="text-xs text-[var(--text-muted)]">{row.last_message_at?formatDate(row.last_message_at):'—'}</span></button>)}</div>}
    {total>0&&<div className="flex items-center justify-between border-t border-[var(--border-subtle)] p-4"><span className="text-xs text-[var(--text-muted)]">{total} conversation{total===1?'':'s'}</span><div className="flex items-center gap-2"><Button size="sm" variant="ghost" disabled={page<=1} onClick={()=>setPage(v=>v-1)}><ChevronLeft size={15}/></Button><span className="text-xs text-[var(--text-muted)]">{page} of {pages}</span><Button size="sm" variant="ghost" disabled={page>=pages} onClick={()=>setPage(v=>v+1)}><ChevronRight size={15}/></Button></div></div>}
    {selected&&<div className="fixed inset-0 z-50 flex justify-end bg-black/55" role="dialog" aria-modal="true" aria-label="Conversation"><button className="flex-1" aria-label="Close conversation" onClick={()=>setSelected(null)}/><aside className="h-full w-full max-w-2xl overflow-y-auto border-l border-[var(--border-subtle)] bg-[var(--surface)]"><header className="sticky top-0 flex items-center justify-between border-b border-[var(--border-subtle)] bg-[var(--surface)] p-5"><div><h2 className="font-semibold">{detail?.business_name??'Loading…'}</h2><p className="text-sm text-[var(--text-muted)]">{detail?.email}</p></div><button onClick={()=>setSelected(null)}><X size={18}/></button></header>{detail&&<div className="space-y-5 p-5"><div className="rounded-lg bg-[var(--background-subtle)] p-3 text-sm text-[var(--text-muted)]">{detail.sync_notice}</div>{detail.suppression&&<p className="text-sm font-medium text-rose-300">{detail.suppression==='unsubscribed'?'Unsubscribed':'Do not contact'}</p>}<div className="space-y-4">{detail.messages.map(message=><article key={message.id} className={`max-w-[90%] rounded-xl border border-[var(--border-subtle)] p-4 ${message.direction==='sent'?'ml-auto bg-[var(--primary-muted)]':'bg-[var(--background-subtle)]'}`}><div className="mb-2 flex flex-wrap justify-between gap-2 text-xs text-[var(--text-muted)]"><span>{message.direction==='sent'?'Sent':'Received'} · {message.from??'Unknown'} → {message.to??'Unknown'}</span><time>{formatDate(message.occurred_at)}</time></div>{message.subject&&<p className="mb-2 font-medium">{message.subject}</p>}<p className="whitespace-pre-wrap text-sm text-[var(--text-secondary)]">{message.body??'Reply content was not stored by the provider integration.'}</p></article>)}</div><Link href={`/dashboard/leads?lead=${detail.id}`} className="text-sm font-medium text-[var(--primary)] hover:underline">View lead</Link></div>}</aside></div>}
  </>
}
