allowBuilds:
  '@google/genai': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
minimumReleaseAgeExclude:
  - '@trigger.dev/core@4.5.6'
  - '@trigger.dev/sdk@4.5.6'
  - '@google/genai@2.15.0'
  - '@trigger.dev/core@4.5.15'
  - '@trigger.dev/sdk@4.5.15'
