'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { Toggle } from '@/components/ui/Toggle'

type Data = { canEdit:boolean; categories:Array<{id:string;name:string;enabled:boolean;locations:string[]}>; locations:Array<{id:string;city:string;suburb:string}>; mode:'template'|'ai_personalised'; automaticFollowups:boolean; schedule:{first:number;second:number;final:number;reconnect:number}; readiness:{complete:boolean;systemActive:boolean;checks:Record<string,boolean>} }

export function CustomerOutreachSettings({ initialData, compact = false }: { initialData: Data; compact?: boolean }) {
  const [data,setData]=useState(initialData); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [saved,setSaved]=useState('')
  const [category,setCategory]=useState(''); const [city,setCity]=useState(''); const [suburb,setSuburb]=useState('')
  async function update(payload:Record<string,unknown>, message:string){setBusy(true);setError('');setSaved('');try{const response=await fetch('/api/customer-outreach',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok)throw new Error(body.error??'Unable to save');setData(body.data);setSaved(message)}catch(cause){setError(cause instanceof Error?cause.message:'Unable to save')}finally{setBusy(false)}}
  const schedule=data.schedule
  const savePreferences=()=>update({action:'preferences',mode:data.mode,automaticFollowups:data.automaticFollowups,...schedule},'Outreach preferences saved')
  const missing=Object.entries(data.readiness.checks).filter(([,ready])=>!ready).map(([key])=>({onboardingComplete:'Finish workspace setup',categories:'Add a target category',locations:'Add a location',mailbox:'Connect a mailbox',personalisation:'Choose personalisation',followups:'Check follow-up timing'}[key]??key))
  function renameCategory(id:string,current:string){const name=window.prompt('Category name',current)?.trim();if(name&&name!==current)void update({action:'update_category',id,name},'Category renamed')}
  return <div className="space-y-5">
    {!compact&&<section><h1 className="text-xl font-semibold text-[var(--text-primary)]">Outreach</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Configure who ReachAgent should find and how your outreach should be prepared.</p></section>}
    <section className={`notice ${data.readiness.complete?'notice--success':'notice--warning'}`}><div><strong>{data.readiness.complete?'Setup complete':'Needs setup'}</strong><p className="mt-1">{data.readiness.complete?'Setup complete — outreach activation is not yet enabled.':missing.join(' · ')}</p></div></section>
    {!compact&&<><section className="surface p-5"><h2 className="font-semibold">Target categories</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Choose the types of businesses ReachAgent should look for.</p><div className="mt-4 space-y-3">{data.categories.map(row=><div key={row.id} className="rounded-lg border border-[var(--border)] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-medium">{row.name}</div><div className="mt-1 text-xs text-[var(--text-muted)]">{row.locations.length?row.locations.join(', '):'Add a target location'}</div></div><div className="flex items-center gap-3">{data.canEdit&&<Button type="button" size="sm" variant="secondary" disabled={busy} onClick={()=>renameCategory(row.id,row.name)}>Rename</Button>}<Toggle checked={row.enabled} disabled={!data.canEdit||busy} label={row.enabled?'Enabled':'Paused'} onChange={enabled=>void update({action:'update_category',id:row.id,enabled},`Category ${enabled?'enabled':'paused'}`)}/></div></div></div>)}{!data.categories.length&&<p className="text-sm text-[var(--text-muted)]">No target categories yet.</p>}</div>{data.canEdit&&<form className="mt-4 flex gap-2" onSubmit={e=>{e.preventDefault();void update({action:'create_category',name:category},'Category added').then(()=>setCategory(''))}}><Input aria-label="New category name" placeholder="e.g. Accounting firms" value={category} onChange={e=>setCategory(e.target.value)}/><Button disabled={busy||!category.trim()}>Add category</Button></form>}</section>
    <section className="surface p-5"><h2 className="font-semibold">Target locations</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Where should ReachAgent look for businesses?</p><div className="mt-4 flex flex-wrap gap-2">{data.locations.map(row=><span key={row.id} className="status-chip status-chip--neutral">{row.suburb?`${row.suburb}, ${row.city}`:row.city}{data.canEdit&&<button className="ml-2" aria-label={`Remove ${row.suburb||row.city}`} onClick={()=>void update({action:'delete_location',id:row.id},'Location removed')}>×</button>}</span>)}</div>{data.canEdit&&<form className="mt-4 grid gap-2 sm:grid-cols-[1fr_1fr_auto]" onSubmit={e=>{e.preventDefault();void update({action:'create_location',city,suburb},'Location added').then(()=>{setCity('');setSuburb('')})}}><Input aria-label="City" placeholder="City" value={city} onChange={e=>setCity(e.target.value)}/><Input aria-label="Suburb or area" placeholder="Suburb / area (optional)" value={suburb} onChange={e=>setSuburb(e.target.value)}/><Button disabled={busy||!city.trim()}>Add location</Button></form>}</section></>}
    <section className="surface p-5" id="personalisation"><h2 className="font-semibold">Personalisation</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{(['template','ai_personalised'] as const).map(mode=><button type="button" key={mode} disabled={!data.canEdit||busy} onClick={()=>setData({...data,mode})} className={`rounded-lg border p-4 text-left ${data.mode===mode?'border-[var(--primary)] bg-[var(--primary-muted)]':'border-[var(--border)]'}`}><strong>{mode==='template'?'Template':'AI Personalised'}</strong><p className="mt-1 text-xs text-[var(--text-muted)]">{mode==='template'?'Uses saved outreach templates.':'Personalises outreach using business context when AI execution is later enabled.'}</p></button>)}</div></section>
    <section className="surface p-5" id="outreach"><h2 className="font-semibold">Follow-ups</h2><div className="mt-3"><Toggle disabled={!data.canEdit||busy} checked={data.automaticFollowups} label="Automatic follow-ups" onChange={automaticFollowups=>setData({...data,automaticFollowups})}/></div><div className="mt-4 grid gap-3 sm:grid-cols-4">{([['first','First follow-up'],['second','Second follow-up'],['final','Final follow-up'],['reconnect','Reconnect']] as const).map(([key,label])=><Input key={key} type="number" min={1} max={key==='reconnect'?730:365} label={label} value={schedule[key]} disabled={!data.canEdit||busy} onChange={e=>setData({...data,schedule:{...schedule,[key]:Number(e.target.value)}})}/>)}</div><p className="mt-2 text-xs text-[var(--text-muted)]">Days after initial contact. Timing must increase in order.</p>{data.canEdit&&<Button className="mt-4" disabled={busy} onClick={savePreferences}>Save preferences</Button>}</section>
    <section className="surface p-5"><h2 className="font-semibold">Outreach state</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">Workspace paused — configuration changes do not start outreach, follow-ups, or reconnects.</p></section>
    {!data.canEdit&&<p className="text-sm text-[var(--text-muted)]">You have view-only access. A workspace owner or admin can change these settings.</p>}{error&&<p role="alert" className="notice notice--error">{error}</p>}{saved&&<p role="status" className="notice notice--success">{saved}</p>}
  </div>
}
