import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const source = (path: string) => readFileSync(resolve(path), 'utf8')

const globals = source('src/app/globals.css')
const filterToolbar = source('src/components/ui/FilterToolbar.tsx')
const modal = source('src/components/ui/Modal.tsx')
const leads = source('src/components/leads/LeadsTable.tsx')
const lifecycle = source('src/components/lifecycle/LifecycleTable.tsx')
const emailReport = source('src/components/email-report/EmailReportDashboard.tsx')
const emailAddresses = source('src/components/email-report/EmailAddressList.tsx')
const failures = source('src/components/delivery-failures/DeliveryFailuresTable.tsx')
const dataQuality = source('src/components/data-quality/DataQualityDashboard.tsx')
const emailLog = source('src/components/email-log/EmailLogTable.tsx')
const deals = source('src/components/deals/DealsTable.tsx')
const dmQueue = source('src/components/dm-queue/DMQueueTable.tsx')
const pipeline = source('src/components/pipeline/KanbanBoard.tsx')
const users = source('src/components/admin/UserManagement.tsx')
const settings = source('src/components/settings/SystemSettings.tsx')

assert.match(filterToolbar, /filter-toolbar__controls/, 'shared filter toolbar has a responsive controls region')
assert.match(globals, /@media \(max-width: 430px\)/, 'compact phone layout is explicitly constrained')
assert.match(globals, /\.desktop-data-table \{ display: none; \}/, 'desktop tables are removed from phone layout')
assert.match(globals, /\.mobile-data-list \{ display: grid; \}/, 'mobile data cards become visible on phones')

assert.match(leads, /ariaLabel="Lead filters"/, 'Leads uses the shared toolbar')
assert.match(leads, /data-testid="leads-mobile-cards"/, 'Leads has a dedicated mobile card view')
assert.match(leads, /Refresh leads/, 'Leads retains an explicit refresh action')
assert.match(lifecycle, /data-testid="lifecycle-mobile-cards"/, 'Lifecycle has a dedicated mobile card view')
assert.match(emailReport, /Export CSV/, 'Email Report retains CSV export')
assert.match(emailReport, /data-testid="email-report-mobile-cards"/, 'Email Report has mobile grouped cards')
assert.match(emailAddresses, /additionalAddressCount/, 'Email Report retains multi-address expansion')
assert.match(emailAddresses, /aria-expanded/, 'multi-address expansion is accessible')
assert.match(failures, /Delete Selected/, 'Delivery Failures retains bulk deletion')
assert.match(failures, /data-testid="delivery-failure-mobile-cards"/, 'Delivery Failures has mobile cards')
assert.match(dataQuality, /data-testid="data-quality-mobile-groups"/, 'Data Quality has mobile issue groups')
assert.match(dataQuality, /aria-expanded=\{open\}/, 'Data Quality mobile groups remain expandable')
assert.match(emailLog, /data-testid="email-log-mobile-cards"/, 'Email Log has mobile cards')
assert.match(deals, /data-testid="deals-mobile-cards"/, 'Deals has mobile cards')
assert.match(deals, /Page \{page\} of \{totalPages\}/, 'Deals server pagination controls remain present')
assert.match(dmQueue, /Page \{page\} of/, 'DM Queue pagination remains present')
assert.match(dmQueue, /md:hidden/, 'DM Queue retains its mobile card view')
assert.match(pipeline, /data-testid="pipeline-mobile-swipe"/, 'Pipeline exposes swipeable mobile columns')
assert.match(users, /data-testid="user-management-mobile-cards"/, 'User Management has mobile cards')
assert.match(settings, /System Settings/, 'Settings forms remain available')
assert.match(settings, /Follow-up Settings/, 'Settings follow-up form remains available')

assert.match(modal, /max-w-\[calc\(100vw-1rem\)\]/, 'modals are viewport constrained')
assert.match(modal, /document\.body\.style\.overflow = 'hidden'/, 'open modals lock background scrolling')
assert.match(modal, /aria-modal="true"/, 'modals retain dialog semantics')

console.log('Responsive page UI tests passed')
