import assert from 'node:assert/strict'
import fs from 'node:fs'

const read=(path:string)=>fs.readFileSync(path,'utf8')
const outreach=read('src/app/dashboard/outreach/page.tsx')
const settings=read('src/app/dashboard/settings/page.tsx')
const api=read('src/app/api/customer-outreach/route.ts')
const ui=read('src/components/outreach/CustomerOutreachSettings.tsx')
const dal=read('src/lib/customer-outreach.ts')
const mailbox=read('src/app/api/mailboxes/route.ts')
const members=read('src/app/api/workspace/members/route.ts')

assert.match(outreach,/CustomerOutreachSettings/,'Outreach must render the customer product UI')
assert.doesNotMatch(outreach,/coming in the next phase/,'Outreach placeholder must be removed')
assert.match(ui,/Target categories/);assert.match(ui,/Target locations/);assert.match(ui,/Template/);assert.match(ui,/AI Personalised/)
assert.match(ui,/Automatic follow-ups/);assert.match(ui,/First follow-up/);assert.match(ui,/Second follow-up/);assert.match(ui,/Final follow-up/);assert.match(ui,/Reconnect/)
assert.match(ui,/outreach activation is not yet enabled/);assert.match(ui,/Workspace paused/)
assert.match(api,/requireApiWorkspaceAdmin/,'Mutations must require workspace admin access')
assert.match(api,/workspaceId/);assert.doesNotMatch(api,/request.*workspace_id|body.*workspace_id/i,'Browser workspace IDs must not be accepted')
assert.match(api,/status: 'paused'/,'New categories must be paused')
assert.doesNotMatch(api,/systemActive|system_active|trigger|generate|sendInitial|scheduleTask/i,'Customer mutations must not enable or execute outreach')
assert.match(api,/input\.first < input\.second && input\.second < input\.final && input\.final < input\.reconnect/)
assert.match(dal,/createWorkspaceServiceClient\(workspaceId\)/,'Reads must be structurally workspace scoped')
assert.match(settings,/CustomerOutreachSettings/,'Settings and Outreach must share canonical controls')
assert.match(settings,/TeamSettings/);assert.match(settings,/UsageLimits/);assert.match(settings,/MailboxSettings/)
assert.match(members,/requireApiWorkspaceAdmin/,'Team mutation must require workspace admin access')
assert.match(mailbox,/publicMailboxConnection/,'Mailbox API must use safe public DTOs')
assert.doesNotMatch(mailbox,/access_token|refresh_token|client_secret/,'Mailbox response route must not expose secrets')
assert.doesNotMatch(ui,/Finder|Researcher|Writer|Sender|Orchestrator|Decision Engine|search cache|raw job/i,'Customer UI must avoid internal terminology')
assert.doesNotMatch(ui,/Aussie Venture|Sydney/,'Customer UI must not contain legacy tenant values')
assert.match(settings,/if \(!workspace\.isPlatformAdmin\)/,'Customer and platform-admin settings must remain separated')
assert.match(settings,/SystemSettings/,'Platform-admin internal settings must remain available')

console.log('Prompt 5 customer Outreach and Settings checks passed')
