'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, ArrowRight, Check, Plus } from 'lucide-react'
import type { OnboardingState } from '@/lib/onboarding'

const labels=['Business','Mailbox','Categories','Locations','Personalisation','Follow-ups','Team','Review','Complete']
export function OnboardingFlow({initialState,userEmail,userName,canManage}:{initialState:OnboardingState;userEmail:string;userName:string|null;canManage:boolean}){
 const router=useRouter(),[state,setState]=useState(initialState),[busy,setBusy]=useState(false),[error,setError]=useState(''),[category,setCategory]=useState(''),[city,setCity]=useState(''),[area,setArea]=useState(''),[inviteEmail,setInviteEmail]=useState(''),[inviteRole,setInviteRole]=useState<'admin'|'member'>('member')
 const step=state.currentStep
 async function save(payload:unknown){setBusy(true);setError('');try{const r=await fetch('/api/onboarding',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(b.error??Object.values(b.fieldErrors??{})[0]??'Unable to save');setState(b.data);return b.data as OnboardingState}catch(e){setError(e instanceof Error?e.message:'Unable to save');return null}finally{setBusy(false)}}
 async function next(){let payload:unknown
  if(step===1)payload={action:'advance',step,data:{workspaceName:state.workspaceName,website:state.website,industry:state.industry,country:state.country,primaryCity:state.primaryCity,senderName:state.senderName,contactEmail:state.contactEmail}}
  else if(step===2)payload={action:'advance',step,data:{skip:state.mailboxSkipped||!state.mailboxConnected}}
  else if(step===3)payload={action:'advance',step,data:{names:state.categories.map(c=>c.name)}}
  else if(step===4)payload={action:'advance',step,data:{locations:state.locations.map(l=>({city:l.city,suburb:l.suburb}))}}
  else if(step===5)payload={action:'advance',step,data:{mode:state.mode}}
  else if(step===6)payload={action:'advance',step,data:{automaticFollowups:state.automaticFollowups,first:state.first,second:state.second,final:state.final,reconnect:state.reconnect}}
  else if(step===7)payload={action:'advance',step,data:inviteEmail?{invite:{email:inviteEmail,role:inviteRole}}:{}}
  else if(step===8)payload={action:'advance',step};else payload={action:'complete',step:9}
  const result=await save(payload);if(result?.status==='completed'){router.push('/dashboard');router.refresh()}
 }
 const input=(key:keyof OnboardingState,label:string,type='text')=><label className="block"><span className="mb-1 block text-sm font-medium">{label}</span><input type={type} value={String(state[key]??'')} onChange={e=>setState({...state,[key]:e.target.value})} className="control-field h-11 w-full px-3" required /></label>
 return <main className="min-h-dvh bg-[var(--background)] px-4 py-8"><div className="mx-auto max-w-4xl"><header className="mb-6 flex justify-between"><div><p className="font-semibold">ReachAgent</p><p className="text-xs text-[var(--text-muted)]">Customer workspace setup</p></div><p className="text-sm">{userName??userEmail}</p></header><nav className="mb-5 overflow-x-auto"><ol className="flex min-w-max gap-2">{labels.map((l,i)=><li key={l} className={`rounded-full px-3 py-1.5 text-xs ${i+1<=step?'bg-[var(--primary)] text-white':'bg-[var(--surface)] text-[var(--text-muted)]'}`}>{i+1}. {l}</li>)}</ol></nav><section className="surface p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-wider text-[var(--primary)]">Step {step} of 9</p><h1 className="mt-1 text-2xl font-semibold">{labels[step-1]}</h1><div className="mt-6 min-h-72">{step===1&&<div className="grid gap-4 sm:grid-cols-2">{input('workspaceName','Business / brand name')}{input('website','Website','url')}{input('industry','Industry / business type')}{input('country','Country')}{input('primaryCity','Primary city')}{input('senderName','Sender / display name')}{input('contactEmail','Contact email','email')}</div>}
 {step===2&&<div><h2 className="font-semibold">Connect your mailbox</h2><p className="mt-2 text-sm text-[var(--text-muted)]">ReachAgent cannot start outreach until a mailbox is connected.</p><div className="mt-5 flex flex-wrap gap-3"><a href="/api/mailboxes/oauth/gmail" className="rounded-lg border px-4 py-2 text-sm font-medium">Connect Gmail</a><a href="/api/mailboxes/oauth/microsoft" className="rounded-lg border px-4 py-2 text-sm font-medium">Connect Microsoft</a></div><p className="mt-5 text-sm">Status: <strong>{state.mailboxConnected?'Connected':'Not connected'}</strong></p><label className="mt-5 flex gap-2 text-sm"><input type="checkbox" checked={state.mailboxSkipped} onChange={e=>setState({...state,mailboxSkipped:e.target.checked})}/>Skip for now (workspace remains paused)</label></div>}
 {step===3&&<div><p className="text-sm text-[var(--text-muted)]">Choose or create categories for your workspace only.</p><div className="mt-4 flex flex-wrap gap-2">{['Restaurants','Cafes','Hotels','Attractions'].map(name=><button type="button" key={name} onClick={()=>!state.categories.some(c=>c.name===name)&&setState({...state,categories:[...state.categories,{id:`new-${name}`,name}]})} className="rounded-full border px-3 py-1.5 text-sm">+ {name}</button>)}</div><div className="mt-4 flex gap-2"><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Custom category" className="control-field h-10 flex-1 px-3"/><button type="button" onClick={()=>{if(category.trim()){setState({...state,categories:[...state.categories,{id:`new-${Date.now()}`,name:category.trim()}]});setCategory('')}}} className="rounded-lg bg-[var(--primary)] px-3 text-white"><Plus/></button></div><Chips values={state.categories.map(c=>c.name)}/></div>}
 {step===4&&<div><p className="text-sm text-[var(--text-muted)]">Where should ReachAgent look for businesses?</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><input value={city} onChange={e=>setCity(e.target.value)} placeholder="City" className="control-field h-10 px-3"/><input value={area} onChange={e=>setArea(e.target.value)} placeholder="Suburb / area (optional)" className="control-field h-10 px-3"/></div><button type="button" onClick={()=>{if(city.trim()){setState({...state,locations:[...state.locations,{id:`new-${Date.now()}`,city:city.trim(),suburb:area.trim()||city.trim()}]});setCity('');setArea('')}}} className="mt-3 rounded-lg border px-3 py-2 text-sm">Add location</button><Chips values={state.locations.map(l=>l.suburb===l.city?l.city:`${l.suburb}, ${l.city}`)}/></div>}
 {step===5&&<Choice value={state.mode} setValue={v=>setState({...state,mode:v as OnboardingState['mode']})} options={[['template','Template','Use your saved templates.'],['ai_personalised','AI Personalised','Store this preference; no AI runs during setup.']]}/>}
 {step===6&&<div><label className="flex gap-2"><input type="checkbox" checked={state.automaticFollowups} onChange={e=>setState({...state,automaticFollowups:e.target.checked})}/>Automatic follow-ups ON/OFF</label><div className="mt-5 grid gap-4 sm:grid-cols-2">{(['first','second','final','reconnect'] as const).map((k,i)=><label key={k}><span className="text-sm">{['First follow-up','Second follow-up','Final follow-up','Reconnect'][i]}</span><input type="number" value={state[k]} onChange={e=>setState({...state,[k]:Number(e.target.value)})} className="control-field mt-1 h-10 w-full px-3"/><span className="text-xs text-[var(--text-muted)]">Days after initial contact</span></label>)}</div><p className="mt-4 text-sm text-[var(--text-muted)]">Saving these timings does not start any schedules.</p></div>}
 {step===7&&<div><div className="overflow-hidden rounded-lg border"><table className="w-full text-left text-sm"><thead><tr className="bg-[var(--surface-hover)]"><th className="p-3">Member</th><th>Role</th><th>State</th></tr></thead><tbody>{state.team.map(m=><tr key={m.id} className="border-t"><td className="p-3">{m.name}<br/><span className="text-xs text-[var(--text-muted)]">{m.email}</span></td><td>{m.role}</td><td>{m.status}</td></tr>)}</tbody></table></div><h2 className="mt-5 font-medium">Add a teammate (optional)</h2><div className="mt-2 flex flex-col gap-2 sm:flex-row"><input type="email" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} placeholder="teammate@example.com" className="control-field h-10 flex-1 px-3"/><select value={inviteRole} onChange={e=>setInviteRole(e.target.value as 'admin'|'member')} className="control-field px-3"><option value="member">Member</option><option value="admin">Admin</option></select></div><p className="mt-2 text-xs text-[var(--text-muted)]">Registered users are added directly. Others receive a pending invitation; no email is sent.</p></div>}
 {step===8&&<Review s={state}/>} {step===9&&<div className="text-center"><Check className="mx-auto text-[var(--success)]" size={42}/><h2 className="mt-4 text-xl font-semibold">Setup ready</h2><p className="mt-2 text-sm text-[var(--text-muted)]">Your workspace will remain paused. Completing setup does not start outreach, AI, discovery, email, follow-ups, or reactivation.</p>{(!state.mailboxConnected||!state.categories.length||!state.locations.length)&&<p className="mt-4 rounded-lg bg-[var(--warning-muted)] p-3 text-sm text-[var(--warning)]">Setup warning: connect a mailbox and add targeting before outreach can be enabled later.</p>}</div>}</div>{error&&<p role="alert" className="mb-4 rounded-lg bg-[var(--error-muted)] p-3 text-sm text-[var(--error)]">{error}</p>}<footer className="flex justify-between border-t pt-4"><button disabled={busy||step===1} onClick={()=>void save({action:'navigate',step:step-1})} className="flex items-center gap-2 px-3 py-2 text-sm"><ArrowLeft size={16}/>Back</button><button disabled={busy||!canManage} onClick={()=>void next()} className="flex items-center gap-2 rounded-lg bg-[var(--primary)] px-4 py-2 text-sm font-semibold text-white">{busy?'Saving…':step===9?'Complete setup':'Continue'}<ArrowRight size={16}/></button></footer></section></div></main>
}
function Chips({values}:{values:string[]}){return <div className="mt-4 flex flex-wrap gap-2">{values.map((v,i)=><span key={`${v}-${i}`} className="rounded-full bg-[var(--primary-muted)] px-3 py-1 text-sm">{v}</span>)}</div>}
function Choice({value,setValue,options}:{value:string;setValue:(v:string)=>void;options:string[][]}){return <div className="grid gap-3 sm:grid-cols-2">{options.map(([v,l,d])=><button type="button" key={v} onClick={()=>setValue(v)} className={`rounded-xl border p-5 text-left ${value===v?'border-[var(--primary)] bg-[var(--primary-muted)]':''}`}><strong>{l}</strong><p className="mt-1 text-sm text-[var(--text-muted)]">{d}</p></button>)}</div>}
function Review({s}:{s:OnboardingState}){const rows=[['Business',`${s.workspaceName} · ${s.industry} · ${s.primaryCity}`],['Mailbox',s.mailboxConnected?'Connected':'Not connected — workspace paused'],['Categories',s.categories.map(c=>c.name).join(', ')||'Missing'],['Locations',s.locations.map(l=>l.suburb).join(', ')||'Missing'],['Mode',s.mode==='template'?'Template':'AI Personalised'],['Follow-ups',`${s.automaticFollowups?'On':'Off'} · Days ${s.first}, ${s.second}, ${s.final}; reconnect ${s.reconnect}`],['Team',`${s.team.length} member/invitation record(s)`]];return <dl className="divide-y rounded-xl border px-4">{rows.map(([a,b])=><div key={a} className="grid gap-1 py-3 sm:grid-cols-[9rem_1fr]"><dt className="text-sm text-[var(--text-muted)]">{a}</dt><dd className="text-sm font-medium">{b}</dd></div>)}</dl>}
