CREATE TABLE city_suburbs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  city TEXT NOT NULL,
  suburb TEXT NOT NULL,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO city_suburbs (city, suburb, active) VALUES
-- Sydney
('Sydney', 'Sydney CBD', true),
('Sydney', 'Parramatta', true),
('Sydney', 'North Sydney', true),
('Sydney', 'Chatswood', true),
('Sydney', 'Bondi', true),
('Sydney', 'Newtown', true),
('Sydney', 'Surry Hills', true),
('Sydney', 'Manly', true),
('Sydney', 'Hurstville', true),
('Sydney', 'Liverpool', true),
('Sydney', 'Bankstown', true),
('Sydney', 'Blacktown', true),
('Sydney', 'Penrith', true),
('Sydney', 'Hornsby', true),
('Sydney', 'Randwick', true),
('Sydney', 'Leichhardt', true),
('Sydney', 'Strathfield', true),
('Sydney', 'Auburn', true),
('Sydney', 'Fairfield', true),
('Sydney', 'Campbelltown', true),
-- Melbourne
('Melbourne', 'Melbourne CBD', true),
('Melbourne', 'St Kilda', true),
('Melbourne', 'Fitzroy', true),
('Melbourne', 'Richmond', true),
('Melbourne', 'South Yarra', true),
('Melbourne', 'Prahran', true),
('Melbourne', 'Carlton', true),
('Melbourne', 'Brunswick', true),
('Melbourne', 'Footscray', true),
('Melbourne', 'Box Hill', true),
('Melbourne', 'Dandenong', true),
('Melbourne', 'Frankston', true),
('Melbourne', 'Werribee', true),
('Melbourne', 'Sunshine', true),
('Melbourne', 'Ringwood', true),
('Melbourne', 'Doncaster', true),
('Melbourne', 'Caulfield', true),
('Melbourne', 'Glen Waverley', true),
('Melbourne', 'Springvale', true),
('Melbourne', 'Coburg', true),
-- Brisbane
('Brisbane', 'Brisbane CBD', true),
('Brisbane', 'South Brisbane', true),
('Brisbane', 'Fortitude Valley', true),
('Brisbane', 'West End', true),
('Brisbane', 'New Farm', true),
('Brisbane', 'Paddington', true),
('Brisbane', 'Woolloongabba', true),
('Brisbane', 'Chermside', true),
('Brisbane', 'Carindale', true),
('Brisbane', 'Logan', true),
('Brisbane', 'Ipswich', true),
('Brisbane', 'Redcliffe', true),
('Brisbane', 'Indooroopilly', true),
('Brisbane', 'Toowong', true),
('Brisbane', 'Sunnybank', true),
('Brisbane', 'Springwood', true),
('Brisbane', 'Browns Plains', true),
('Brisbane', 'Strathpine', true),
('Brisbane', 'Caboolture', true),
('Brisbane', 'Beenleigh', true),
-- Perth
('Perth', 'Perth CBD', true),
('Perth', 'Fremantle', true),
('Perth', 'Subiaco', true),
('Perth', 'Cottesloe', true),
('Perth', 'Joondalup', true),
('Perth', 'Rockingham', true),
('Perth', 'Mandurah', true),
('Perth', 'Midland', true),
('Perth', 'Cannington', true),
('Perth', 'Morley', true),
('Perth', 'Armadale', true),
('Perth', 'Stirling', true),
('Perth', 'Scarborough', true),
('Perth', 'Mount Lawley', true),
('Perth', 'Victoria Park', true),
('Perth', 'Nedlands', true),
('Perth', 'Canning Vale', true),
('Perth', 'Balcatta', true),
('Perth', 'Osborne Park', true),
('Perth', 'Bentley', true),
-- Adelaide
('Adelaide', 'Adelaide CBD', true),
('Adelaide', 'Glenelg', true),
('Adelaide', 'North Adelaide', true),
('Adelaide', 'Norwood', true),
('Adelaide', 'Prospect', true),
('Adelaide', 'Unley', true),
('Adelaide', 'Marion', true),
('Adelaide', 'Tea Tree Gully', true),
('Adelaide', 'Modbury', true),
('Adelaide', 'Elizabeth', true),
('Adelaide', 'Salisbury', true),
('Adelaide', 'Morphett Vale', true),
('Adelaide', 'Mount Barker', true),
('Adelaide', 'Victor Harbor', true),
('Adelaide', 'Port Adelaide', true),
('Adelaide', 'Hindmarsh', true),
('Adelaide', 'Henley Beach', true),
('Adelaide', 'Burnside', true),
('Adelaide', 'Campbelltown', true),
('Adelaide', 'Mitcham', true);
