export { evaluateLeadShadow } from './evaluator'
export type { EvaluateLeadShadowDependencies, ShadowEvaluationObserver } from './evaluator'
export { evaluateShadowBatch, summarizeShadowResults, MAX_SHADOW_BATCH_SIZE, DEFAULT_SHADOW_CONCURRENCY } from './batch'
export { selectShadowLeadIds } from './selector'
export type { ShadowSampleSelector } from './selector'
export { assertShadowSafeExecution } from './safety'
export type { ShadowSafetyState } from './safety'
export { createReadOnlySupabaseClient } from './read-only-client'
export type { ReadOnlyClientAudit } from './read-only-client'
export { EXPECTED_DIFFERENCE_REGISTER, SHADOW_CLASSIFICATION_ALIASES } from './expected-differences'
export { SHADOW_TARGETS } from './types'
export type { ShadowTarget, ShadowSafetyRequest, ShadowComparisonResult, ShadowEvaluationOutcome, ShadowComparisonSummary } from './types'
export { createShadowRuntimeClient, runShadowReport, validateProductionShadowCredentials } from './runtime'
export type { ShadowRuntimeClient, RunShadowReportInput, ShadowRuntimeReport } from './runtime'
export { SYNTHETIC_SHADOW_COHORTS } from './synthetic-cohorts'
export type { SyntheticShadowCohort } from './synthetic-cohorts'
export { V1_DATA_COMPATIBILITY_REPORT } from './compatibility'
export type { V1DataCompatibilityCheck } from './compatibility'
